-- Ativa RLS em todas as tabelas principais
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_client_assoc ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_solutions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manufacturers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operation_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.association_types ENABLE ROW LEVEL SECURITY;