// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veujcxwewbtasxbsyvrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldWpjeHdld2J0YXN4YnN5dnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTA0NTEsImV4cCI6MjA2MDM4NjQ1MX0.K3EkNqnXVpB69vwwypS-jpZLBsUxWgq7igJjkWUWODU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);